languageCode = "el"
languageName = "Έλληνικα"
displayName = ":greece:"
isoCode = "el"
weight = 2
rtl = false
contentdir = "content/el"

title = "DTK Computing"
# logo = "img/logo.jpg"
description = ""
copyright = "&copy; 2022 Congo contributors"

dateFormat = "2 January 2006"

[author]
  name = "iJimHD"
  image = "img/author.jpg"
  headline = ""
  bio = ""
  links = [
    { github = "https://github.com/ijimhd" },
    { telegram = "https://t.me/ijimhd" },
    { gitlab = "https://gitlab.com/ijimhd" },
  ]
